INSERT INTO categoria (id, nome) VALUES (1, 'Eletronicos');
INSERT INTO categoria (id, nome) VALUES (2, 'Livros');
INSERT INTO categoria (id, nome) VALUES (3, 'Casa');
INSERT INTO categoria (id, nome) VALUES (4, 'Esportes');
INSERT INTO categoria (id, nome) VALUES (5, 'Papelaria');
INSERT INTO produto (id, nome, preco, categoria_id) VALUES (1, 'Mouse', 80.00, 1);
INSERT INTO produto (id, nome, preco, categoria_id) VALUES (2, 'Livro Java', 120.00, 2);
INSERT INTO produto (id, nome, preco, categoria_id) VALUES (3, 'Caneca', 35.00, 3);
INSERT INTO produto (id, nome, preco, categoria_id) VALUES (4, 'Bola', 95.00, 4);
INSERT INTO produto (id, nome, preco, categoria_id) VALUES (5, 'Caderno', 25.00, 5);
INSERT INTO cliente (id, nome, email, telefone) VALUES (1, 'Ana Silva', 'cliente1@exemplo.com', '11999990001');
INSERT INTO cliente (id, nome, email, telefone) VALUES (2, 'Bruno Costa', 'cliente2@exemplo.com', '11999990002');
INSERT INTO cliente (id, nome, email, telefone) VALUES (3, 'Carla Souza', 'cliente3@exemplo.com', '11999990003');
INSERT INTO cliente (id, nome, email, telefone) VALUES (4, 'Diego Lima', 'cliente4@exemplo.com', '11999990004');
INSERT INTO cliente (id, nome, email, telefone) VALUES (5, 'Eva Martins', 'cliente5@exemplo.com', '11999990005');
INSERT INTO pedido (id, data, status, valor_total, cliente_id) VALUES (1, '2026-09-10 10:00:00', 'CONFIRMADO', 80.00, 1);
INSERT INTO pedido (id, data, status, valor_total, cliente_id) VALUES (2, '2026-09-11 10:00:00', 'CONFIRMADO', 120.00, 2);
INSERT INTO pedido (id, data, status, valor_total, cliente_id) VALUES (3, '2026-09-12 10:00:00', 'CONFIRMADO', 35.00, 3);
INSERT INTO pedido (id, data, status, valor_total, cliente_id) VALUES (4, '2026-09-13 10:00:00', 'CONFIRMADO', 95.00, 4);
INSERT INTO pedido (id, data, status, valor_total, cliente_id) VALUES (5, '2026-09-14 10:00:00', 'CONFIRMADO', 25.00, 5);
INSERT INTO item_pedido (id, quantidade, valor_unitario, pedido_id, produto_id) VALUES (1, 1, 80.00, 1, 1);
INSERT INTO item_pedido (id, quantidade, valor_unitario, pedido_id, produto_id) VALUES (2, 1, 120.00, 2, 2);
INSERT INTO item_pedido (id, quantidade, valor_unitario, pedido_id, produto_id) VALUES (3, 1, 35.00, 3, 3);
INSERT INTO item_pedido (id, quantidade, valor_unitario, pedido_id, produto_id) VALUES (4, 1, 95.00, 4, 4);
INSERT INTO item_pedido (id, quantidade, valor_unitario, pedido_id, produto_id) VALUES (5, 1, 25.00, 5, 5);
INSERT INTO pagamento (id, valor, data, status, tipo, pedido_id) VALUES (1, 80.00, '2026-09-10 10:05:00', 'APROVADO', 'PIX', 1);
INSERT INTO pagamento (id, valor, data, status, tipo, pedido_id) VALUES (2, 120.00, '2026-09-11 10:05:00', 'APROVADO', 'PIX', 2);
INSERT INTO pagamento (id, valor, data, status, tipo, pedido_id) VALUES (3, 35.00, '2026-09-12 10:05:00', 'APROVADO', 'PIX', 3);
INSERT INTO pagamento (id, valor, data, status, tipo, pedido_id) VALUES (4, 95.00, '2026-09-13 10:05:00', 'APROVADO', 'PIX', 4);
INSERT INTO pagamento (id, valor, data, status, tipo, pedido_id) VALUES (5, 25.00, '2026-09-14 10:05:00', 'APROVADO', 'PIX', 5);
INSERT INTO categoria_evento (id, nome, descricao) VALUES (1, 'Tecnologia', 'Palestras de tecnologia');
INSERT INTO categoria_evento (id, nome, descricao) VALUES (2, 'Educacao', 'Encontros educacionais');
INSERT INTO categoria_evento (id, nome, descricao) VALUES (3, 'Saude', 'Eventos sobre saude');
INSERT INTO categoria_evento (id, nome, descricao) VALUES (4, 'Cultura', 'Atividades culturais');
INSERT INTO categoria_evento (id, nome, descricao) VALUES (5, 'Negocios', 'Eventos empresariais');
INSERT INTO local (id, nome, endereco, capacidade) VALUES (1, 'Auditorio Central', 'Rua A, 100', 200);
INSERT INTO local (id, nome, endereco, capacidade) VALUES (2, 'Sala Azul', 'Rua B, 200', 80);
INSERT INTO local (id, nome, endereco, capacidade) VALUES (3, 'Centro Cultural', 'Rua C, 300', 300);
INSERT INTO local (id, nome, endereco, capacidade) VALUES (4, 'Sala Verde', 'Rua D, 400', 60);
INSERT INTO local (id, nome, endereco, capacidade) VALUES (5, 'Teatro Municipal', 'Rua E, 500', 250);
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (1, 'Marina Alves', 'Especialista convidado para o evento', 'palestrante1@exemplo.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (2, 'Rafael Souza', 'Especialista convidado para o evento', 'palestrante2@exemplo.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (3, 'Lucia Martins', 'Especialista convidado para o evento', 'palestrante3@exemplo.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (4, 'Pedro Lima', 'Especialista convidado para o evento', 'palestrante4@exemplo.com');
INSERT INTO palestrante (id, nome, mini_bio, email) VALUES (5, 'Beatriz Costa', 'Especialista convidado para o evento', 'palestrante5@exemplo.com');
INSERT INTO participante (id, nome, email, telefone) VALUES (1, 'Joao Silva', 'participante1@exemplo.com', '11988880001');
INSERT INTO participante (id, nome, email, telefone) VALUES (2, 'Ana Oliveira', 'participante2@exemplo.com', '11988880002');
INSERT INTO participante (id, nome, email, telefone) VALUES (3, 'Carlos Mendes', 'participante3@exemplo.com', '11988880003');
INSERT INTO participante (id, nome, email, telefone) VALUES (4, 'Fernanda Rocha', 'participante4@exemplo.com', '11988880004');
INSERT INTO participante (id, nome, email, telefone) VALUES (5, 'Paula Ribeiro', 'participante5@exemplo.com', '11988880005');
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (1, 'Encontro de Java', 'Evento aberto ao publico', '2026-10-10 09:00:00', '2026-10-10 17:00:00', 60, 'ABERTO', 1, 1, 1);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (2, 'Jornada de Educacao', 'Evento aberto ao publico', '2026-10-11 09:00:00', '2026-10-11 17:00:00', 60, 'ABERTO', 2, 2, 2);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (3, 'Forum de Saude', 'Evento aberto ao publico', '2026-10-12 09:00:00', '2026-10-12 17:00:00', 60, 'ABERTO', 3, 3, 3);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (4, 'Festival Cultural', 'Evento aberto ao publico', '2026-10-13 09:00:00', '2026-10-13 17:00:00', 50, 'ABERTO', 4, 4, 4);
INSERT INTO evento (id, nome, descricao, data_inicio, data_fim, capacidade, status, categoria_id, local_id, palestrante_id) VALUES (5, 'Seminario de Negocios', 'Evento aberto ao publico', '2026-10-14 09:00:00', '2026-10-14 17:00:00', 60, 'ABERTO', 5, 5, 5);
INSERT INTO inscricao (id, data_inscricao, status, evento_id, participante_id) VALUES (1, '2026-09-21 10:00:00', 'CONFIRMADA', 1, 1);
INSERT INTO inscricao (id, data_inscricao, status, evento_id, participante_id) VALUES (2, '2026-09-21 10:00:00', 'CONFIRMADA', 2, 2);
INSERT INTO inscricao (id, data_inscricao, status, evento_id, participante_id) VALUES (3, '2026-09-21 10:00:00', 'CONFIRMADA', 3, 3);
INSERT INTO inscricao (id, data_inscricao, status, evento_id, participante_id) VALUES (4, '2026-09-21 10:00:00', 'CONFIRMADA', 4, 4);
INSERT INTO inscricao (id, data_inscricao, status, evento_id, participante_id) VALUES (5, '2026-09-21 10:00:00', 'CONFIRMADA', 5, 5);
